site_name: hashicorp/tfe Terraform Provider - Contributor Guide
site_description: 'Contributor documentation and reference for the
                   hashicorp/tfe Terraform provider'
copyright: HashiCorp
repo_name: hashicorp/terraform-provider-tfe
repo_url: https://github.com/hashicorp/terraform-provider-tfe
edit_uri: "https://github.com/hashicorp/terraform-provider-tfe/tree/main/docs"

nav:
  - Welcome: index.md
  - Contribute:
      - Development Environment: development-environment.md
      - Test Infrastructure: test-infrastructure.md
      - Contribution Guides:
          - Testing: testing.md
          - Introducing Beta Features: beta.md
          - Debugging: debugging.md
          - Backwards Compatibility: backwards-compatibility.md
      - Acceptance Tests: writing-acceptance-tests.md
      - Changelog Process: changelog-process.md

theme:
  name: material
  logo: images/hashicorp.png
  favicon: images/hashicorp-black.png
  palette:
    scheme: hashicorp
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github
  font: false
  features:
    - navigation.instant
    - content.tabs.link

plugins:
  - search:
      lang:
        - en

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: "#"

extra_css:
  - stylesheets/extra.css
