name: Azure Schema List
on:
  workflow_dispatch:

jobs:
  Update:
    name: Update Azure Schema List
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ARM Schemas
        uses: actions/checkout@v2.4.0
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          
      - name: Copy ARM Schema Files
        run: |
          mkdir ./schemas
          mkdir ./schemas-preview
          mkdir ./schemas-viewdefinition
          mkdir ./schemas-common
          for dir in ./azure-resource-manager-schemas/schemas/20* ; do
            if [ "$dir" -ne "*preview" ]; then
              cp -urf $dir/*.json ./schemas
              cp -urf $dir/**/*.json ./schemas
            else
              cp -urf $dir/*.json ./schemas-preview
              cp -urf $dir/**/*.json ./schemas-preview
            fi
          done
          cp -urf ./azure-resource-manager-schemas/schemas/common ./schemas-common
          cp -urf ./azure-resource-manager-schemas/schemas/viewdefinition ./schemas-viewdefinition
          # cp -urf ./azure-resource-manager-schemas/schemas/20*/*.json ./schemas
          # rm -rf ./schemas/*-preview
          # rm -rf ./schemas/*-privatepreview

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo

      - name: Consolidate Latest ARM Schema Version Files
        run: |
          cd ./myrepo
          if [ -d ./azure ]; then
            mkdir ./azure
          fi
          cd ./azure
          if [ -d ./schemas ]; then
            cp -urf ../../schemas ./schemas
          else
            mkdir ./schemas
            cp -rf ../../schemas ./schemas
          fi
          if [ -d ./schemas-preview ]; then
            cp -urf ../../schemas-preview ./schemas-preview
          else
            mkdir ./schemas-preview
            cp -rf ../../schemas-preview ./schemas-preview
          fi
          if [ -d ./schemas-common ]; then
            cp -urf ../../schemas-common ./schemas-common
          else
            mkdir ./schemas-common
            cp -rf ../../schemas-common ./schemas-common
          fi
          if [ -d ./viewdefinition ]; then
            cp -urf ../../viewdefinition ./viewdefinition
          else
            mkdir ./viewdefinition
            cp -rf ../../viewdefinition ./viewdefinition
          fi

      - name: Commit And Push ARM Schema Files
        run: |
          cd ./myrepo
          date > ./updatedARMschema.txt
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./schemas-merged
          git add ./schemas-preview
          git add ./updatedARMschema.txt
          git commit -m "ARM Schema List updated by getAzureSchema workflow"
          git push
