name: Azure Schema List
on:
  workflow_dispatch:

jobs:
  Update:
    name: Update Azure Schema List
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ARM Schemas
        uses: actions/checkout@v2.4.0
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          
      - name: Copy ARM Schema Files
        run: |
          mkdir ./schemas
          mkdir ./schemas-preview
          cp -rf ./azure-resource-manager-schemas/schemas/20* ./schemas
          cp -rf ./azure-resource-manager-schemas/schemas/20*-preview ./schemas-preview
          cp -rf ./azure-resource-manager-schemas/schemas/20*-privatepreview ./schemas-preview
          cp -rf ./azure-resource-manager-schemas/schemas/viewdefinition/0.0.1-preview ./schemas-preview
          cp -rf ./azure-resource-manager-schemas/schemas/common ./schemas
          rm -rf ./schemas/*-preview
          rm -rf ./schemas/*-privatepreview

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          
      - name: Consolidate Latest ARM Schema Version Files
        run: |
          if [ -d ./myrepo/schemas-merged ]; then
            echo "Found ./myrepo/schemas-merged"
          else
            mkdir ./myrepo/schemas-merged
          fi
          for dir in ./schemas/* ; do
            for fn in $dir/*.json ; do
              cp -u $fn ./myrepo/schemas-merged
            done
          done
          cp -ur ./schemas-preview ./myrepo

      - name: Commit And Push ARM Schema Files
        run: |
          cd ./myrepo
          date > ./updatedARMschema.txt
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./schemas-merged
          git add ./schemas-preview
          git add ./updatedARMschema.txt
          git commit -m "ARM Schema List updated by getAzureSchema workflow"
          git push
