name: Azure Schema List
on:
  workflow_dispatch:

jobs:
  Update:
    name: Update Azure Schema List
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ARM Schemas
        uses: actions/checkout@v2.4.0
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          submodules: true
          
      - name: Copy ARM Schema Files
        run: |
          mkdir ./az
          cd ./az
          mkdir ./schemas
          mkdir ./schemaspreview
          mkdir ./common
          mkdir ./viewdefinition
          cd ..
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]' ; do
            cp -ur $dir/. ./az/schemas/
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-preview' ; do
            cp -ur $dir/. './az/schemaspreview/'
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-privatepreview' ; do
            cp -ur $dir/. './az/schemaspreview/'
          done
          cp -r ./azure-resource-manager-schemas/schemas/common/. ./az/common/
          cp -r ./azure-resource-manager-schemas/schemas/viewdefinition/. ./az/viewdefinition/
        continue-on-error: true

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          fetch-depth: 0

      - name: Consolidate Latest ARM Schema Version Files
        run: |
          cd ./myrepo
          if [ -d ./azure ]; then
            echo "Found ./azure"
          else
            mkdir ./azure
          fi
          cd ./azure
          cp -ur ../../az/schemas/. ./schemas/
          cp -ur ../../az/schemaspreview/. ./schemaspreview/
          cp -ur ../../az/common/. ./common/
          cp -ur ../../az/viewdefinition/. ./viewdefinition/
          
      - name: Commit And Push ARM Schema Files
        run: |
          cd ./myrepo
          date > ./azure/updatedARMschema.txt
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./azure
          git commit -m "ARM Schema List updated by getAzureSchema workflow"
          git push
