name: Hashicorp Schema Lists
on:
  workflow_dispatch:

jobs:
  update:
    name: Update HashiCorp Schema Lists
    runs-on: ubuntu-latest

    steps:

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          fetch-depth: 0

      - name: Break Git Cache Link
        run: |
          git rm --cached terraform/terraform-plugin-sdk
        continue-on-error: true

      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform-plugin-sdk
          fetch-depth: 0
          
      - name: Copy HashiCorp Files
        run: |
          cd ./myrepo
          ls -l
          if [ -d ./terraform ]; then
            cd ./terraform
          else
            mkdir ./terraform
            cd ./terraform
          fi
          cp -ru ../../terraform-plugin-sdk .
        continue-on-error: true

      - name: Commit And Push HashiCorp Schema Dir
        run: |
          cd ./myrepo
          date > ./terraform/hashi-updated.txt
          git config user.name getHashiSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./terraform
          git commit -m "Commit by getHashiSchemas workflow"
          git push
