name: Hashicorp Schema Lists
on:
  workflow_dispatch:

jobs:
  update:
    name: Update HashiCorp Schema Lists
    runs-on: ubuntu-latest

    steps:

      - name: Checkout My Repo
        uses: actions/checkout@v3
        with:
          repository: tekowalsky/Azure-Providers
          path: ./AzProviders
          fetch-depth: 0

      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v3
        with:
          repository: terraform/terraform-provider-azurerm
          path: ./terraform/terraform-provider-azurerm
          fetch-depth: 0
          
      - name: Break Git Cache Link
        run: |
          git rm --cached terraform/terraform-provider-azurerm
        continue-on-error: true
          
      - name: Copy HashiCorp Files
        run: |
          cd ./AzProviders
          ls -l
          if(test-path "./terraform" -pathtype Leaf){
            cd ./terraform
          } else {
            mkdir ./terraform
            cd ./terraform
          }
          copy-item -r "../../terraform-provider-azurerm" .
          $("Category Resource Attribute Type") | export-csv ./tf_resources.csv
          get-childitem "./terraform-provider-azurerm/" | ?{$_.PSIsContainer -eq $true} | {
            $D=$_
            $D | %{
              $Dr = $_
              $P = $("$(($Dr.PSPath).split("::")[1])"+"/parse")
              $AzF = get-childitem -Path "$($P)" -File -Include "*.go" -Exclude "*_test.go"
              $S = $(($Dr.PSPath).split("::")[1]).split("/")
              $cnt = ($S.count) - 1
              $Cat = $S[$($cnt)]
              $T = 0
              $DSfiles | %{
                $F = $_
                $Fn = ($F.name).split(".")[0].replace("_","")
                $C = get-content $F
                $C | %{
                  $R = $_
                  $L = $("type "+"$($Cat)")
                  if($T -eq "1"){
                    if($R -eq "}"){
                      $T = "0"
                    } else {
                      $dL = $("$($Cat)"+" $($R)")
                      $dL | export-csv -append ./tf_resources.csv
                    }
                  }
                  if($R -like "$($L)*"){
                    $T = "1"
                  }
                }
              }
              $Resfiles | %{
                $F = $_
                $C = get-content $F
                $C | %{
                  $R = $_

                }
              }
            }
          }

        shell: pwsh

      - name: Commit And Push HashiCorp Schema Dir
        run: |
          cd ./myrepo
          date > ./terraform/hashi-updated.txt
          git config user.name getHashiSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./terraform
          git commit -m "Commit by getHashiSchemas workflow"
          git push
          