name: Update Hashicorp Schema Lists
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform-plugin-sdk
          fetch-depth: 0
          
      - name: SetupSchemaDir
        run: |
          if [ -d ./schemas ]; then
            if [ -d ./schemas/terraform-plugin-sdk ]; then
              echo "Found ./schemas/terraform-plugin-sdk"
            else
              mkdir ./schemas/terraform-plugin-sdk
            fi
          else
            mkdir ./schemas
            mkdir ./schemas/terraform-plugin-sdk
          fi
          ls -lr ./terraform-plugin-sdk > ./schemas/terraform-plugin-sdk.txt
          cp -rf ./terraform-plugin-sdk ./schemas/terraform-plugin-sdk

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          fetch-depth: 0
          
      - name: MakeMerged
        run: |
          src='./schemas/terraform-plugin-sdk'
          dest='./myrepo/schemas-terraform-plugin-sdk'
          if [ -d "$dest" ]; then
            echo "Found $dest"
          else
            mkdir "$dest"
          fi
          cp -f "$src"'.txt' './myrepo'
          for fn in "$src"/*'.json' ; do
            cp -u "$fn" "$dest"
          for dir in "$src"/* ; do
            for fn in "$dir"/*'.json' ; do
              cp -u "$fn" "$dest"
            done
          done
          # cp -ur ./schemas-preview ./myrepo
        continue-on-error: true

      - name: CommitAndPush
        run: |
          cd './myrepo'
          date > ./hashi-updated.txt
          git config user.name getHashiSchemas-Workflow
          git config user.email github-actions@github.com
          git add './hashi-updated.txt'
          git add './schemas-terraform-plugin-sdk'
          git commit -m "Commit by getHashiSchemas workflow"
          git push
