name: Update Hashicorp Schema Lists
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform-plugin-sdk
          fetch-depth: 0
          
      - name: Copy HashiCorp Files
        run: |
          if [ -d ./schemas ]; then
            if [ -d ./schemas/terraform-plugin-sdk ]; then
              echo "Found ./schemas/terraform-plugin-sdk"
            else
              mkdir ./schemas/terraform-plugin-sdk
            fi
          else
            mkdir ./schemas
            mkdir ./schemas/terraform-plugin-sdk
          fi
          ls -ltR ./terraform-plugin-sdk/**/* > ./schemas/terraform-plugin-sdk.files.txt
          cp -rf ./terraform-plugin-sdk ./schemas/terraform-plugin-sdk

      - name: Checkout My Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          fetch-depth: 0
          
      - name: Make My HashiCorp Schema Dir
        run: |
          cd ./myrepo
          if [ -d ./schemas-terraform-plugin-sdk ]; then
            echo "Found ./myrepo/schemas-terraform-plugin-sdk"
          else
            mkdir ./schemas-terraform-plugin-sdk
          fi
          cp -f ../schemas/terraform-plugin-sdk.files.txt .
          for fn in ../schemas/terraform-plugin-sdk/*.json ; do
            cp -u $fn ./schemas-terraform-plugin-sdk
          for dir in ../schemas/terraform-plugin-sdk/* ; do
            for fn in $dir/*.json ; do
              cp -u $fn ./schemas-terraform-plugin-sdk
            done
          done
          # cp -ur ./schemas-preview .
        continue-on-error: true

      - name: Commit And Push HashiCorp Schema Dir
        run: |
          cd ./myrepo
          date > ./hashi-updated.txt
          git config user.name getHashiSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./hashi-updated.txt
          git add ./schemas-terraform-plugin-sdk
          git commit -m "Commit by getHashiSchemas workflow"
          git push
