name: Update Schema Lists
on:
  pull_request:
    branches:
      - '!*'
      - main
  push:
    branches:
      - '!*'
      - dev
  workflow_dispatch:

  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  Update:
    name: Update Schema Lists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repo
        uses: actions/checkout@v3
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          ref: schemas
          fetch-depth: 0

      - name: Clear old data
        run: |
          cp ./myrepo/README.md ./README.md.bak
          cd ./myrepo
          ls -l
          rm -rf ./.
          cp ../README.md.bak ./README.md
          rm -rf ../README.md.bak
          echo "* @tekowalsky" > ./CODEOWNERS
          ls -l
          cd ..
        continue-on-error: true
  
      - name: Checkout ARM Schemas
        uses: actions/checkout@v3
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          # submodules: true

      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform/terraform-plugin-sdk
          fetch-depth: 0
          submodules: true
          
      - name: Checkout HashiCorp Azurerm Provider Repo
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-azurerm
          path: ./terraform/terraform-provider-azurerm
          fetch-depth: 0
          submodules: true
          
      - name: Checkout HashiCorp TFE Provider Repo
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-tfe
          path: ./terraform/terraform-provider-tfe
          fetch-depth: 0
          submodules: true

      # - name: Break Git Cache Links
      #   run: |
      #     git rm --cached terraform/terraform-plugin-sdk
      #     git rm --cached terraform/terraform-provider-azurerm
      #     git rm --cached terraform/terraform-provider-tfe
      #   continue-on-error: true

      - name: ARM Schema Files
        run: |
          echo "Setup ARM Schema directories"
          date > ./myrepo/lastSchemasUpdate.txt
          cd ./myrepo  # added line
          mkdir ./azure  # added line
          # mkdir ./az
          cd ./azure  # added line
          # cd ./az
          mkdir ./schemas
          mkdir ./schemaspreview
          mkdir ./common
          mkdir ./viewdefinition
          cd ..
          cd ..  # added line (to go back to root)
          echo "Consolidate ARM Schema Files"
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]' ; do
            cp -r $dir/. ./myrepo/azure/schemas/  # added line
            # cp -r $dir/. ./az/schemas/
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-preview' ; do
            cp -r $dir/. ./myrepo/azure/schemaspreview/ # added line
            # cp -r $dir/. './az/schemaspreview/'
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-privatepreview' ; do
            cp -r $dir/. ./myrepo/azure/schemaspreview/ # added line
            # cp -r $dir/. './az/schemaspreview/'
          done
          cp -r ./azure-resource-manager-schemas/schemas/common/. ./myrepo/azure/common/  # added line
          cp -r ./azure-resource-manager-schemas/schemas/viewdefinition/. ./myrepo/azure/viewdefinition/  # added line
          # cp -r ./azure-resource-manager-schemas/schemas/common/. ./az/common/
          # cp -r ./azure-resource-manager-schemas/schemas/viewdefinition/. ./az/viewdefinition/
        # continue-on-error: true

      # - name: Consolidate ARM Schema Files
      #   run: |
      #     cd ./myrepo
      #     mkdir ./azure
      #     cd ./azure
      #     cp -r ../../az/schemas/. ./schemas/
      #     cp -r ../../az/schemaspreview/. ./schemaspreview/
      #     cp -r ../../az/common/. ./common/
      #     cp -r ../../az/viewdefinition/. ./viewdefinition/
      #     cd ..
      #   continue-on-error: true

      - name: Copy HashiCorp Files
        run: |
          cd ./myrepo
          mkdir ./terraform
          cd ./terraform
          mkdir terraform-plugin-sdk
          mkdir terraform-provider-azurerm
          mkdir terraform-provider-tfe
          # cd terraform-plugin-sdk
          cd ..  # added line (return to ./myrepo root)
          cd ..  # added line (return to root)
          cp -r ./terraform/terraform-plugin-sdk/. ./myrepo/terraform/terraform-plugin-sdk/  # added line
          # cp -r ../../terraform/terraform-plugin-sdk/* .
          # cd ..
          # mkdir terraform-provider-azurerm
          # cd terraform-provider-azurerm
          cp -r ./terraform/terraform-provider-azurerm/. ./myrepo/terraform/terraform-provider-azurerm/  # added line
          # cp -r ../../terraform/terraform-provider-azurerm/* .
          # cd ..
          # mkdir terraform-provider-tfe
          # cd terraform-provider-tfe
          cp -r ./terraform/terraform-provider-tfe/. ./myrepo/terraform/terraform-provider-tfe/  # added line
          # cp -r ../../terraform/terraform-provider-tfe/* .
          # cd ..
          # cd ..
        # continue-on-error: true

      - name: Commit ARM and Hashicorp Schema Files
        if: ${{ success() }}
        run: |
          cd ./myrepo
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./azure
          git add ./terraform
          git commit -m "Schema Lists updated by getSchemas workflow"
          git push
          cd ..

      - name: Force cleanup of runner
        if: ${{ always() }}
        run: |
          rm -r ./myrepo
          rm -r ./azure-resource-manager-schemas
          rm -r ./terraform
          sudo shutdown -r now