name: Update Schema Lists
on:
  pull_request:
    branches:
      - '!*'
      - main
  push:
    branches:
      - '!*'
      - dev
  workflow_dispatch:

  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  Update_Schemas:
    name: Update Schema Lists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repo
        uses: actions/checkout@v3
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          ref: schemas
          fetch-depth: 0

      - name: Clear old data
        if: ${{ success() }}
        run: |
          cp ./myrepo/README.md ./README.md.bak
          cd ./myrepo
          if [ -d ./terraform ]; then
            git config user.name GetSchemas-Workflow
            git config user.email github-actions@github.com
            for dir in './terraform' ; do
              git rm -r --cached $dir
              git rm -r $dir
            done
            git commit -m "Clear old data"
            git push  
          fi
          rm -rf ./**
          cp ../README.md.bak ./README.md
          echo "* @tekowalsky" > ./CODEOWNERS
          cd ..
          rm -rf ./README.md.bak
        # continue-on-error: true

      - name: Checkout ARM Schemas
        if: ${{ success() }}
        uses: actions/checkout@v3
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          # submodules: true

      - name: Checkout HashiCorp Plugin SDK Repo
        if: ${{ success() }}
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform/terraform-plugin-sdk
          fetch-depth: 0
          submodules: true
          
      - name: Checkout HashiCorp Azurerm Provider Repo
        if: ${{ success() }}
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-azurerm
          path: ./terraform/terraform-provider-azurerm
          fetch-depth: 0
          submodules: true
          
      - name: Checkout HashiCorp TFE Provider Repo
        if: ${{ success() }}
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-tfe
          path: ./terraform/terraform-provider-tfe
          fetch-depth: 0
          submodules: true
          
      - name: ARM Schema Files
        if: ${{ success() }}
        run: |
          echo "Setup ARM Schema directories"
          date > ./myrepo/lastSchemasUpdate.txt
          cd ./myrepo
          mkdir ./azure
          cd ./azure
          mkdir ./schemas
          mkdir ./schemaspreview
          mkdir ./common
          mkdir ./viewdefinition
          cd ..
          cd ..  # to go back to root
          echo "Consolidate ARM Schema Files"
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]' ; do
            cp -r $dir/. ./myrepo/azure/schemas/
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-preview' ; do
            cp -r $dir/. ./myrepo/azure/schemaspreview/
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-privatepreview' ; do
            cp -r $dir/. ./myrepo/azure/schemaspreview/
          done
          cp -r ./azure-resource-manager-schemas/schemas/common/. ./myrepo/azure/common/
          cp -r ./azure-resource-manager-schemas/schemas/viewdefinition/. ./myrepo/azure/viewdefinition/

      - name: Copy HashiCorp Files
        if: ${{ success() }}
        run: |
          # cd ./myrepo
          echo "Creating a temporary directory to hold HashiCorp files in the root."
          mkdir ./terraform-tmp
          cd ./terraform-tmp

          mkdir terraform-plugin-sdk
          mkdir ../myrepo/terraform/terraform-plugin-sdk
          cd terraform-plugin-sdk
          for dir in '../../terraform/terraform-plugin-sdk' ; do
            cp -r $dir/. .
          done
          cd .. # return to ./terraform
          cp -r ./terraform-plugin-sdk/** ../myrepo/terraform/terraform-plugin-sdk/
          # cp -r ./terraform/terraform-plugin-sdk/. ./myrepo/terraform/terraform-plugin-sdk/

          mkdir terraform-provider-azurerm
          mkdir ../myrepo/terraform/terraform-provider-azurerm
          cd terraform-provider-azurerm
          for dir in '../../terraform/terraform-provider-azurerm' ; do
            cp -r $dir/. .
          done
          cd .. # return to ./terraform
          cp -r ./terraform-provider-azurerm/** ../myrepo/terraform/terraform-provider-azurerm/
          # cp -r ./terraform/terraform-provider-azurerm/. ./myrepo/terraform/terraform-provider-azurerm/

          mkdir terraform-provider-tfe
          mkdir ../myrepo/terraform/terraform-provider-tfe
          cd terraform-provider-tfe
          for dir in '../../terraform/terraform-provider-tfe' ; do
            cp -r $dir/. .
          done
          cd .. # return to ./terraform
          cp -r ./terraform-provider-tfe/** ../myrepo/terraform/terraform-provider-tfe/
          # cp -r ./terraform/terraform-provider-tfe/. ./myrepo/terraform/terraform-provider-tfe/

          # cd ..  # return to ./myrepo root
          cd ..  # return to root
          rm -rf ./myrepo/terraform/**/.git
          rm -rf ./myrepo/terraform/**/.github
          rm -rf ./terraform-tmp
          rm -rf ./terraform
          rm -rf ./**/.gitmodules

      - name: Commit ARM and Hashicorp Schema Files
        if: ${{ success() }}
        run: |
          cd ./myrepo
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./README.md
          git add ./CODEOWNERS
          git add ./lastSchemasUpdate.txt
          git add ./azure/**
          git add ./terraform/**
          git commit -m "Schema Lists updated by getSchemas workflow"
          git push
          cd ..

      - name: Force cleanup of runner
        if: ${{ always() }}
        run: |
          rm -rf ./**