name: Update Schema List
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          
      - name: GetSchemaDir
        run: |
          mkdir ./schemas
          cp -rf ./azure-resource-manager-schemas/schemas/20* ./schemas
          rm -rf ./schemas/*-preview
          rm -rf ./schemas/*-privatepreview
          mkdir ./merged
          for dir in ./schemas/* ; do
            cp -u ./schemas/$dir/*.json ./merged
          done
          ls -l ./merged
