name: Update Schema Lists
on:
  workflow_dispatch:

jobs:
  Update:
    name: Update Schema Lists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repo
        uses: actions/checkout@v3
        with:
          repository: tekowalsky/Azure-Providers
          path: ./myrepo
          ref: schemas
          fetch-depth: 0

      - name: Checkout ARM Schemas
        uses: actions/checkout@v3
        with:
          repository: Azure/azure-resource-manager-schemas
          path: ./azure-resource-manager-schemas
          fetch-depth: 0
          submodules: true

      - name: Checkout HashiCorp Plugin SDK Repo
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-plugin-sdk
          path: ./terraform-plugin-sdk
          fetch-depth: 0
          submodules: true

      # - name: Break git cache link
      #  run: |
      #    git rm --cached terraform-plugin-sdk

      - name: Clear old data
        run: |
          if [ -d ./az ]; then
            rm -rf ./az
          fi
          cp ./myrepo/README.md ./
          cd ./myrepo
          if [ -d ./azure ]; then
            rm -rf ./azure
          fi
          if [ -d ./terraform ]; then
            rm -rf ./terraform
          fi
          if [ -d ./github ]; then
            rm -rf ./github
          fi
          rm -rf ./*
          rm -rf ./*.*
          cp ../README.md ./
          rm -rf ../README.md
          cd ..
        continue-on-error: true

      - name: Collect ARM Schema Files
        run: |
          mkdir ./az
          cd ./az
          mkdir ./schemas
          mkdir ./schemaspreview
          mkdir ./common
          mkdir ./viewdefinition
          cd ..
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]' ; do
            cp -ur $dir/. ./az/schemas/
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-preview' ; do
            cp -ur $dir/. './az/schemaspreview/'
          done
          for dir in './azure-resource-manager-schemas/schemas/20[1-2][0-9]-[0-1][0-9]-[0-3][0-9]-privatepreview' ; do
            cp -ur $dir/. './az/schemaspreview/'
          done
          cp -r ./azure-resource-manager-schemas/schemas/common/. ./az/common/
          cp -r ./azure-resource-manager-schemas/schemas/viewdefinition/. ./az/viewdefinition/
        continue-on-error: true

      - name: Consolidate ARM Schema Files
        run: |
          cd ./myrepo
          mkdir ./azure
          cd ./azure
          cp -ur ../../az/schemas/. ./schemas/
          cp -ur ../../az/schemaspreview/. ./schemaspreview/
          cp -ur ../../az/common/. ./common/
          cp -ur ../../az/viewdefinition/. ./viewdefinition/
          cd ..
        continue-on-error: true

      - name: Copy HashiCorp Files
        run: |
          cd ./myrepo
          mkdir ./terraform
          cd ./terraform
          cp -ru ../../terraform-plugin-sdk .
          cd ..
        continue-on-error: true

      - name: Commit ARM and Hashicorp Schema Files
        run: |
          cd ./myrepo
          date > ./azure/ARMschemaDate.txt
          date > ./terraform/hashiDate.txt
          git config user.name GetSchemas-Workflow
          git config user.email github-actions@github.com
          git add ./azure
          git add ./terraform
          git commit -m "Schema Lists updated by getSchemas workflow"
          git push
